### ISSUE TITLE
Moonlight non-copyleft license request

### ISSUE THREAD

**Issue by prepare** [prepare/HtmlKit#7]
Hello @jstedfast,  
This is not about your HtmlKit.

But This is about  **Moonlight source license**
https://github.com/mono/moon
(I can't create an issue in that repo, so I ask you here)

I'm working on the HtmlRenderer project
(https://github.com/LayoutFarm/HtmlRenderer).

I want to study your Moonlight work.
and Integrate some part of your code/experiences
(esp in src folder) into my repo .
I think the code is worth to others too.
But the current license is LGPL.

Since Mono runtime license has changed to MIT.

_My request:_   
Could you (and team) change a license of
https://github.com/mono/moon
to a non-copyleft one too? 

Thank you

WinterDev :)

**Comment by jstedfast** [comment]
Unfortunately the Mono team does not have the ability to change the license because we no longer own the copyright to the code. It is owned by Novell/Attachmate who would probably not be willing to relicense.

You could ask, but I don't know who to contact on their side.

**Comment by prepare** [comment]
Thank you :)
